// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<void> processFile(std::string path);

ets::Task<void> processFile(std::string path) {
    const std::string copy = ets::concat(path, std::string(".copy"));
    const ets::Result<bool> written = (co_await writeFileAsync(path, std::string("hello")));
    if ((written.isOk() == false)) {
        printError(written.error());
    }
    const ets::Result<bool> appended = (co_await appendFileAsync(path, std::string(" async files")));
    if ((appended.isOk() == false)) {
        printError(appended.error());
    }
    const ets::Result<std::string> contents = (co_await readFileAsync(path));
    if (contents.isOk()) {
        print(contents.value());
    } else {
        printError(contents.error());
    }
    const ets::Result<bool> copied = (co_await copyFileAsync(path, copy));
    if ((copied.isOk() == false)) {
        printError(copied.error());
    }
    const ets::Result<bool> exists = (co_await fileExistsAsync(copy));
    if (exists.isOk()) {
        print(std::string("copy exists="), exists.value());
    }
    const ets::Result<bool> removedPath = (co_await removeFileAsync(path));
    const ets::Result<bool> removedCopy = (co_await removeFileAsync(copy));
    if ((removedPath.isOk() == false)) {
        printError(removedPath.error());
    }
    if ((removedCopy.isOk() == false)) {
        printError(removedCopy.error());
    }
    co_return;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    ets::syncWait(processFile(argument(1.0)));
    return 0;
}
