// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T>
concept Describable = requires(T value) {
    { value.description() } -> std::same_as<std::string>;
};

struct Motor {
    double power;

    std::string description() const {
        return ets::concat(std::string("Motor de "), numberToString((*this).power), std::string(" CV"));
    }
};

struct Car {
    Motor motor;
    std::string model;

    std::string description() const {
        return ets::concat((*this).model, std::string(" con "), (*this).motor.description());
    }
};

template <Describable T0>
void show(const T0& value);

static Motor motor = Motor{150.0};
static Car car = Car{motor, std::string("Coupe")};

template <Describable T0>
void show(const T0& value) {
    print(value.description());
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    show(motor);
    show(car);
    print(std::string("Potencia leída por composición: "), car.motor.power, std::string(" CV"));
    return 0;
}
