// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Point {
    double x;
    double y;
    std::string label;

    void constructor(double x, double y, const std::string& label) {
        ((*this).x = x);
        ((*this).y = y);
        ((*this).label = label);
    }

    double sum() const {
        return ((*this).x + (*this).y);
    }
};

struct Pair {
    double first;
    double second;
};

struct Counter {
    double value;

    void constructor(double initial) {
        ((*this).value = initial);
    }

    double current() const {
        return (*this).value;
    }
};

struct Empty {
};

void increment(Counter& counter);

static Point p = Point{3.0, 4.0, std::string("origin")};
static Pair pair = Pair{10.0, 20.0};
static Counter c = Counter{100.0};
static Empty e = Empty{};

void increment(Counter& counter) {
    (counter.value = (counter.value + 1.0));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(p.sum());
    print(p.label);
    print(p.x);
    print(p.y);
    (p.label = std::string("moved"));
    print(p.label);
    print(pair.first);
    print(pair.second);
    increment(c);
    increment(c);
    increment(c);
    print(c.current());
    print(std::string("ok"));
    return 0;
}
