// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T = double>
struct Box {
    T value;
};

template <typename T = double>
T makeNum(const T& v);

static Box<double> b = Box<double>{7.0};

template <typename T>
T makeNum(const T& v) {
    return v;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(numberToString(b.value));
    print(numberToString(makeNum<double>(42.0)));
    print(numberToString(makeNum<double>(99.0)));
    return 0;
}
