// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string head(const std::vector<std::string>& arr);

static std::vector<double> nums = std::vector<double>{std::move(1.0), std::move(2.0), std::move(3.0)};
static std::vector<double> source = std::vector<double>{std::move(100.0), std::move(200.0), std::move(300.0), std::move(400.0)};

std::string head(const std::vector<std::string>& arr) {
    return arr[static_cast<std::size_t>(0.0)];
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    const auto __ets_destructure_1 = nums;
    const auto first = __ets_destructure_1[0];
    const auto second = __ets_destructure_1[1];
    const auto third = __ets_destructure_1[2];
    const std::vector<double> __ets_destructure_2 = std::vector<double>{std::move(10.0), std::move(20.0)};
    const auto x = __ets_destructure_2[0];
    const auto y = __ets_destructure_2[1];
    std::vector<std::string> __ets_destructure_3 = std::vector<std::string>{std::move(std::string("Ana")), std::move(std::string("López"))};
    auto name = __ets_destructure_3[0];
    auto surname = __ets_destructure_3[1];
    const std::vector<std::string> __ets_destructure_4 = std::vector<std::string>{std::move(std::string("alpha")), std::move(std::string("beta")), std::move(std::string("gamma"))};
    const auto a = __ets_destructure_4[0];
    const auto b = __ets_destructure_4[1];
    const auto c = __ets_destructure_4[2];
    const std::vector<double> __ets_destructure_5 = source;
    const auto p = __ets_destructure_5[0];
    const auto q = __ets_destructure_5[1];
    const auto r = __ets_destructure_5[2];
    print(first);
    print(second);
    print(third);
    print(x);
    print(y);
    print(name);
    print(surname);
    (surname = std::string("García"));
    print(surname);
    print(head(std::vector<std::string>{std::move(a), std::move(b), std::move(c)}));
    print(((p + q) + r));
    return 0;
}
