// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<double> delay(double ms, double value);
ets::Task<std::string> collectInOrder();
ets::Task<double> sumInOrder();
ets::Task<std::string> empty();

ets::Task<double> delay(double ms, double value) {
    (co_await sleep(ms));
    co_return value;
}

ets::Task<std::string> collectInOrder() {
    const std::vector<ets::Task<double>> promises = ([](std::vector<ets::Task<double>> dst) -> std::vector<ets::Task<double>> { dst.push_back(std::move(delay(5.0, 100.0))); dst.push_back(std::move(delay(5.0, 200.0))); dst.push_back(std::move(delay(5.0, 300.0))); return dst; })(std::vector<ets::Task<double>>());
    std::string acc = std::string("");
    for (const auto& v_iter : promises) {
    auto v_awaited = co_await(v_iter);
    auto v = v_awaited;
        (acc = ets::concat(acc, numberToString(v), std::string(" ")));
    }
    co_return acc;
}

ets::Task<double> sumInOrder() {
    const std::vector<ets::Task<double>> promises = ([](std::vector<ets::Task<double>> dst) -> std::vector<ets::Task<double>> { dst.push_back(std::move(delay(10.0, 1.0))); dst.push_back(std::move(delay(10.0, 2.0))); dst.push_back(std::move(delay(10.0, 3.0))); return dst; })(std::vector<ets::Task<double>>());
    double acc = 0.0;
    for (const auto& v_iter : promises) {
    auto v_awaited = co_await(v_iter);
    auto v = v_awaited;
        (acc = (acc + v));
    }
    co_return acc;
}

ets::Task<std::string> empty() {
    const std::vector<ets::Task<double>> promises = std::vector<ets::Task<double>>();
    std::string acc = std::string("done");
    for (const auto& v_iter : promises) {
    auto v_awaited = co_await(v_iter);
    auto v = v_awaited;
        (acc = numberToString(v));
    }
    co_return acc;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(ets::syncWait(collectInOrder()));
    print(numberToString(ets::syncWait(sumInOrder())));
    print(ets::syncWait(empty()));
    return 0;
}
