// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static ets::Result<bool> written = fs.writeFileSync(std::string("/tmp/fs-demo.txt"), std::string("hola fs\n"));
static ets::Result<std::string> contents = fs.readFileSync(std::string("/tmp/fs-demo.txt"));
static ets::Task<ets::Result<std::string>> asyncRead = fs.readFile(std::string("/tmp/fs-demo.txt"));
static ets::Result<std::string> asyncResult = ets::syncWait(asyncRead);
static ets::Result<bool> removed = fs.unlinkSync(std::string("/tmp/fs-demo.txt"));

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    if (fs.existsSync(std::string("/tmp/fs-demo.txt"))) {
        const ets::Result<bool> removed = fs.unlinkSync(std::string("/tmp/fs-demo.txt"));
        if ((removed.isOk() == false)) {
            console.error(std::string("unlink previo falló:"), removed.error());
        }
    }
    if ((written.isOk() == false)) {
        console.error(std::string("write falló:"), written.error());
    }
    console.log(std::string("escrito OK"));
    if ((contents.isOk() == false)) {
        console.error(std::string("read falló:"), contents.error());
    }
    console.log(std::string("leído sync:"), contents.value());
    if ((asyncResult.isOk() == false)) {
        console.error(std::string("async read falló:"), asyncResult.error());
    }
    console.log(std::string("leído async:"), asyncResult.value());
    if ((removed.isOk() == false)) {
        console.error(std::string("unlink falló:"), removed.error());
    }
    console.log(std::string("borrado OK"));
    return 0;
}
