// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<void> handleClient(ets::TcpConnection connection);
ets::Task<void> serve();

ets::Task<void> handleClient(ets::TcpConnection connection) {
    const ets::Result<std::string> request = (co_await readTcp(connection, 16384.0));
    if (request.isOk()) {
        const std::string body = std::string("Hello from Estatic TS");
        const std::string response = ets::concat(std::string("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: "), numberToString(length(body)), std::string("\r\nConnection: close\r\n\r\n"), body);
        const ets::Result<double> written = (co_await writeTcp(connection, response));
        if ((written.isOk() == false)) {
            printError(written.error());
        }
    } else {
        printError(request.error());
    }
    closeTcp(connection);
    co_return;
}

ets::Task<void> serve() {
    const ets::Result<ets::TcpListener> opened = listenTcp(std::string("0.0.0.0"), 8080.0);
    if ((opened.isOk() == false)) {
        printError(opened.error());
        co_return;
    }
    const ets::TcpListener listener = opened.value();
    print(std::string("Listening on http://127.0.0.1:8080"));
    while (true) {
        const ets::Result<ets::TcpConnection> accepted = (co_await acceptTcp(listener));
        if (accepted.isOk()) {
            spawn(handleClient(accepted.value()));
        } else {
            printError(accepted.error());
        }
    }
    co_return;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    ets::syncWait(serve());
    return 0;
}
