// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

void printIfString(const ets_json::Value& v, const std::string& key);
void printArrayLen(const ets_json::Value& v);
void demoObject();
void demoArray();
void demoNested();

void printIfString(const ets_json::Value& v, const std::string& key) {
    if (jsonIsObject(v)) {
        const ets_json::Value field = jsonObjectGet(v, key);
        if (jsonIsString(field)) {
            print(jsonAsString(field));
        }
    }
}

void printArrayLen(const ets_json::Value& v) {
    if (jsonIsArray(v)) {
        print(jsonArrayLength(v));
    }
}

void demoObject() {
    const std::string src = std::string("{\"name\": \"alice\", \"age\": 30, \"active\": true}");
    const ets_json::Value v = JSON.parseValue(src);
    printIfString(v, std::string("name"));
    const ets_json::Value age = jsonObjectGet(v, std::string("age"));
    if (jsonIsNumber(age)) {
        print(jsonAsNumber(age));
    }
}

void demoArray() {
    const std::string src = std::string("[\"a\", \"b\", \"c\"]");
    const ets_json::Value v = JSON.parseValue(src);
    printArrayLen(v);
    const ets_json::Value first = jsonArrayGet(v, 0.0);
    if (jsonIsString(first)) {
        print(jsonAsString(first));
    }
}

void demoNested() {
    const std::string src = std::string("{\"tags\": [\"admin\", \"user\"], \"data\": 42}");
    const ets_json::Value v = JSON.parseValue(src);
    const ets_json::Value tags = jsonObjectGet(v, std::string("tags"));
    printArrayLen(tags);
    const ets_json::Value data = jsonObjectGet(v, std::string("data"));
    if (jsonIsNumber(data)) {
        print(jsonAsNumber(data));
    }
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demoObject();
    demoArray();
    demoNested();
    return 0;
}
