// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static double radius = 5.0;
static double circleArea = ((3.14159265 * radius) * radius);
static double now = Date.now();
static double epoch = Date.utc(1970.0, 0.0, 1.0);
static std::string quoted = JSON.stringify(std::string("hola"));
static std::string parsed = JSON.parse(std::string("\"hello world\""));

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(Math.floor(3.7));
    print(Math.ceil(3.2));
    print(Math.round(3.5));
    print(Math.abs((-7.0)));
    print(Math.sqrt(16.0));
    print(Math.pow(2.0, 10.0));
    print(Math.min(5.0, 9.0));
    print(Math.max(5.0, 9.0));
    print(Math.round(circleArea));
    print((now > 0.0));
    print(epoch);
    print(quoted);
    print(parsed);
    return 0;
}
