// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::vector<std::string> args = process.argv();
static std::string escaped = JSON.stringify(std::string("hola\nmundo\t\"!\""));

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    console.log(std::string("--- path ---"));
    console.log(std::string("dirname('/tmp/a/b.txt') ="), path.dirname(std::string("/tmp/a/b.txt")));
    console.log(std::string("basename('/tmp/a/b.txt') ="), path.basename(std::string("/tmp/a/b.txt")));
    console.log(std::string("extname('/tmp/a/b.txt') ="), path.extname(std::string("/tmp/a/b.txt")));
    console.log(std::string("isAbsolute('/tmp/a') ="), path.isAbsolute(std::string("/tmp/a")));
    console.log(std::string("isAbsolute('relativo') ="), path.isAbsolute(std::string("relativo")));
    console.log(std::string("normalize('/tmp/a/../b//c') ="), path.normalize(std::string("/tmp/a/../b//c")));
    console.log(std::string("join(['/tmp','a','b','c.txt']) ="), path.join(std::vector<std::string>{std::move(std::string("/tmp")), std::move(std::string("a")), std::move(std::string("b")), std::move(std::string("c.txt"))}));
    console.log(std::string("resolve(['.','build','app']) ="), path.resolve(std::vector<std::string>{std::move(std::string(".")), std::move(std::string("build")), std::move(std::string("app"))}));
    console.log(std::string("--- process ---"));
    console.log(std::string("argc ="), process.argc());
    console.log(std::string("argv length ="), length(args));
    if ((length(args) > 0.0)) {
        console.log(std::string("argv[0] ="), args[static_cast<std::size_t>(0.0)]);
    }
    console.log(std::string("cwd ="), process.cwd());
    console.log(std::string("--- JSON ---"));
    console.log(std::string("stringify ="), escaped);
    return 0;
}
