// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Box {
    double value;
};

ets::Optional<Box> maybeBox(bool b);

static ets::Optional<Box> present = maybeBox(true);
static ets::Optional<double> v1 = optionalAndThen(present, [](auto _ets_optional_chain) { return optionalSome(_ets_optional_chain.value); });
static ets::Optional<Box> absent = maybeBox(false);
static ets::Optional<double> v2 = optionalAndThen(absent, [](auto _ets_optional_chain) { return optionalSome(_ets_optional_chain.value); });
static ets::Optional<double> chained = optionalAndThen(maybeBox(true), [](auto _ets_optional_chain) { return optionalSome(_ets_optional_chain.value); });

ets::Optional<Box> maybeBox(bool b) {
    if (b) {
        return optionalSome<Box>(Box{42.0});
    }
    return optionalNone<Box>();
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(optionalValueOr(v1, (-1.0)));
    print(optionalValueOr(v2, (-1.0)));
    print(optionalValueOr(chained, (-1.0)));
    return 0;
}
