// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string describe(double value);
std::string describe(const std::string& value);
template <typename T>
std::string describe(const T& value);
template <typename... T>
void logAll(const T&... values);

std::string describe(double value) {
    return ets::concat(std::string("number="), numberToString(value));
}

std::string describe(const std::string& value) {
    return ets::concat(std::string("string="), value);
}

template <typename T>
std::string describe(const T& value) {
    return std::string("generic");
}

template <typename... T>
void logAll(const T&... values) {
    print(values...);
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(describe(42.0));
    print(describe(std::string("hello")));
    print(describe<bool>(true));
    logAll(std::string("mixed: "), 10.0, std::string(", "), true);
    logAll<double, std::string>(7.0, std::string(" explicit"));
    return 0;
}
