// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static double n = 42.0;
static std::string s = std::string("literal");
static std::variant<double, std::string> y = std::string("hello");
static double baseOptional = 10.0;
static ets::Optional<double> maybe = optionalSome(baseOptional);

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(numberToString(n));
    print(s);
    print(y);
    print(numberToString(optionalValueOr(maybe, (-1.0))));
    return 0;
}
