// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"
#include "runtime/ets_tls.hpp"

ets::Task<void> secureServer(std::string certificate, std::string privateKey);

ets::Task<void> secureServer(std::string certificate, std::string privateKey) {
    const ets::Result<ets::TlsContext> contextResult = createTlsServer(certificate, privateKey);
    if ((contextResult.isOk() == false)) {
        printError(contextResult.error());
        co_return;
    }
    const ets::Result<ets::TcpListener> opened = listenTcp(std::string("127.0.0.1"), 34443.0);
    if ((opened.isOk() == false)) {
        printError(opened.error());
        co_return;
    }
    const ets::CancellationSource source = createCancellation();
    const ets::TcpListener listener = opened.value();
    print(std::string("READY"));
    const ets::Result<ets::TlsConnection> accepted = (co_await acceptTls(listener, contextResult.value(), 5000.0, cancellationToken(source)));
    if (accepted.isOk()) {
        const ets::TlsConnection connection = accepted.value();
        const ets::Result<std::string> request = (co_await readTls(connection, 4096.0, 5000.0, cancellationToken(source)));
        if (request.isOk()) {
            const ets::Result<double> response = (co_await writeTls(connection, ets::concat(std::string("secure:"), request.value()), 5000.0, cancellationToken(source)));
            if ((response.isOk() == false)) {
                printError(response.error());
            }
        }
        closeTls(connection);
    } else {
        printError(accepted.error());
    }
    closeTcp(listener);
    co_return;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    ets::syncWait(secureServer(argument(1.0), argument(2.0)));
    return 0;
}
