// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

void demoBasic();
void demoScope();

void demoBasic() {
    std::string greeting = std::string("hello");
    print(greeting);
    ets::Optional<double> maybe = optionalSome(42.0);
    print(numberToString(optionalValueOr(maybe, (-1.0))));
    std::vector<double> items = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};
    print(numberToString(items[static_cast<std::size_t>(0.0)]));
    print(numberToString(items[static_cast<std::size_t>(2.0)]));
}

void demoScope() {
    {
        std::string local = std::string("inside");
        print(local);
    }
    print(std::string("after-block"));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demoBasic();
    demoScope();
    return 0;
}
