// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<void> cancelSoon(ets::CancellationSource source);
ets::Task<void> cancellationDemo(double port);

ets::Task<void> cancelSoon(ets::CancellationSource source) {
    (co_await sleep(20.0));
    cancel(source);
    co_return;
}

ets::Task<void> cancellationDemo(double port) {
    const ets::CancellationSource source = createCancellation();
    const ets::CancellationToken token = cancellationToken(source);
    const ets::Result<ets::TcpListener> opened = listenTcp(std::string("127.0.0.1"), port);
    if ((opened.isOk() == false)) {
        printError(opened.error());
        co_return;
    }
    const ets::TcpListener listener = opened.value();
    spawn(cancelSoon(source));
    const ets::Result<ets::TcpConnection> accepted = (co_await acceptTcpUntil(listener, 5000.0, token));
    if ((accepted.isOk() == false)) {
        print(accepted.error());
    }
    closeTcp(listener);
    co_return;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    ets::syncWait(cancellationDemo(34567.0));
    return 0;
}
