// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Inventory {
    std::vector<double> quantities;
    std::tuple<std::string, bool> metadata;

    double first() const {
        return (*this).quantities[static_cast<std::size_t>(0.0)];
    }
};

static std::vector<double> values = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};
static std::tuple<std::string, bool> metadata = std::make_tuple(std::string("active"), true);
static Inventory inventory = Inventory{values, metadata};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    (values[static_cast<std::size_t>(1.0)] = 25.0);
    print(std::string("Elementos: "), length(values));
    print(std::string("Segundo: "), values[static_cast<std::size_t>(1.0)]);
    print(std::string("Etiqueta: "), std::get<0>(metadata));
    print(std::string("Primer inventario: "), inventory.first());
    return 0;
}
