// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    console.log(std::string("Hola desde console.log"));
    console.info(std::string("Info:"), 42.0, true);
    console.debug(std::string("Debug en stderr? No, stdout:"), (1.0 + 1.0));
    console.warn(std::string("Esto sale por stderr"));
    console.error(std::string("Error grave:"), std::string("fallo X"));
    console.log(std::string("Mezclando tipos:"), std::string("texto"), 99.0, false);
    return 0;
}
