// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string greet(const std::string& name, const std::string& greeting = std::string("Hola"));
double scale(double value, double factor = 2.0, double offset = 100.0);
void demo();

std::string greet(const std::string& name, const std::string& greeting) {
    return ets::concat(greeting, std::string(", "), name, std::string("!"));
}

double scale(double value, double factor, double offset) {
    return ((value * factor) + offset);
}

void demo() {
    console.log(greet(std::string("Mundo")));
    console.log(greet(std::string("Ana"), std::string("Adiós")));
    console.log(ets::concat(std::string("scale 5:"), numberToString(scale(5.0))));
    console.log(ets::concat(std::string("scale 5,3:"), numberToString(scale(5.0, 3.0))));
    console.log(ets::concat(std::string("scale 5,3,1:"), numberToString(scale(5.0, 3.0, 1.0))));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demo();
    return 0;
}
