// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::vector<double> empty = std::vector<double>();
static std::vector<double> two = std::vector<double>{std::move(10.0), std::move(20.0)};
static std::vector<double> three = std::vector<double>{std::move(100.0), std::move(200.0), std::move(300.0)};
static std::vector<std::string> tags = std::vector<std::string>{std::move(std::string("alpha"))};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    const auto __ets_destructure_1 = empty;
    const auto x = (__ets_destructure_1.size() > 0 ? __ets_destructure_1[0] : (1.0));
    const auto y = (__ets_destructure_1.size() > 1 ? __ets_destructure_1[1] : (2.0));
    const auto z = (__ets_destructure_1.size() > 2 ? __ets_destructure_1[2] : (3.0));
    const auto __ets_destructure_2 = two;
    const auto a = (__ets_destructure_2.size() > 0 ? __ets_destructure_2[0] : (1.0));
    const auto b = (__ets_destructure_2.size() > 1 ? __ets_destructure_2[1] : (2.0));
    const auto c = (__ets_destructure_2.size() > 2 ? __ets_destructure_2[2] : (3.0));
    const auto __ets_destructure_3 = three;
    const auto p = (__ets_destructure_3.size() > 0 ? __ets_destructure_3[0] : (1.0));
    const auto q = (__ets_destructure_3.size() > 1 ? __ets_destructure_3[1] : (2.0));
    const auto r = (__ets_destructure_3.size() > 2 ? __ets_destructure_3[2] : (3.0));
    const auto __ets_destructure_4 = tags;
    const auto t1 = (__ets_destructure_4.size() > 0 ? __ets_destructure_4[0] : (std::string("default")));
    const auto t2 = (__ets_destructure_4.size() > 1 ? __ets_destructure_4[1] : (std::string("fallback")));
    print(x);
    print(y);
    print(z);
    print(a);
    print(b);
    print(c);
    print(p);
    print(q);
    print(r);
    print(t1);
    print(t2);
    return 0;
}
