// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

double square(double x);
std::string greet(const std::string& name);

static double PI = 3.14159;
static double E = 2.71828;

double square(double x) {
    return (x * x);
}

std::string greet(const std::string& name) {
    return ets::concat(std::string("hello "), name);
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(PI);
    print(E);
    print(square(5.0));
    print(greet(std::string("alice")));
    print(PI);
    print(square(7.0));
    return 0;
}
