// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::vector<double> xs = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};
static ets::Map<std::string, double> m = ets::Map<std::string, double>{};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    for (std::size_t i_i = 0; i_i < (xs).size(); ++i_i) {
        double i = static_cast<double>(i_i);
        print(ets::concat(std::string("idx="), numberToString(i)));
    }
    m.set(std::string("alpha"), 1.0);
    m.set(std::string("beta"), 2.0);
    for (const auto& k_pair : (m).data()) {
        auto k = k_pair.first;
        print(ets::concat(std::string("key="), k));
    }
    return 0;
}
