// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string twice(const std::function<std::string(double)>& action, double base);
void demo();

static std::function<std::string(const std::string&)> toUpper = [](const std::string& input) -> std::string {
    return input;
};

std::string twice(const std::function<std::string(double)>& action, double base) {
    return ets::concat(action(base), std::string("|"), action((base + 1.0)));
}

void demo() {
    console.log(toUpper(std::string("hola")));
    console.log(twice([=](double value) -> std::string {
        return numberToString(value);
    }, 10.0));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demo();
    return 0;
}
