// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

double factorial(double n);

static std::string name = std::string("mundo");
static double value = factorial(5.0);

double factorial(double n) {
    double result = 1.0;
    double i = 2.0;
    while ((i <= n)) {
        (result = (result * i));
        (i = (i + 1.0));
    }
    return result;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(ets::concat(std::string("Hola, "), name));
    print(value);
    return 0;
}
