// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T>
concept Named = requires(T value) {
    { value.name() } -> std::same_as<std::string>;
};

struct User {
    std::string label;

    std::string name() const {
        return (*this).label;
    }
};

template <Named T0>
void show(const T0& value);

static User user = User{std::string("Ada")};

template <Named T0>
void show(const T0& value) {
    print(value.name());
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    show(user);
    return 0;
}
