// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

void demo();

void demo() {
    ets::Map<std::string, double> scores = ets::Map<std::string, double>{};
    scores.set(std::string("alice"), 10.0);
    scores.set(std::string("bob"), 20.0);
    scores.set(std::string("carol"), 30.0);
    console.log(ets::concat(std::string("tamaño:"), numberToString(scores.size())));
    std::string bobTxt = std::string("no");
    if (scores.has(std::string("bob"))) {
        (bobTxt = std::string("sí"));
    }
    console.log(ets::concat(std::string("tiene bob:"), bobTxt));
    std::string delTxt = std::string("no");
    if (scores.removeKey(std::string("carol"))) {
        (delTxt = std::string("sí"));
    }
    console.log(ets::concat(std::string("borrar carol:"), delTxt));
    console.log(ets::concat(std::string("tras borrar:"), numberToString(scores.size())));
    double pairsCount = 0.0;
    scores.forEach([&](double value, const std::string& key) mutable -> void {
        (pairsCount = (pairsCount + 1.0));
    });
    console.log(ets::concat(std::string("pares contados:"), numberToString(pairsCount)));
    ets::Set<std::string> seen = ets::Set<std::string>{};
    seen.add(std::string("rojo"));
    seen.add(std::string("verde"));
    seen.add(std::string("rojo"));
    console.log(ets::concat(std::string("set size:"), numberToString(seen.size())));
    std::string verdeTxt = std::string("no");
    if (seen.has(std::string("verde"))) {
        (verdeTxt = std::string("sí"));
    }
    console.log(ets::concat(std::string("set tiene verde:"), verdeTxt));
    seen.removeKey(std::string("rojo"));
    console.log(ets::concat(std::string("set tras delete:"), numberToString(seen.size())));
    double tagsCount = 0.0;
    seen.forEach([&](const std::string& value) mutable -> void {
        (tagsCount = (tagsCount + 1.0));
    });
    console.log(ets::concat(std::string("set forEach total:"), numberToString(tagsCount)));
    scores.clear();
    seen.clear();
    console.log(ets::concat(std::string("vacío map:"), numberToString(scores.size())));
    console.log(ets::concat(std::string("vacío set:"), numberToString(seen.size())));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demo();
    return 0;
}
