// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Counter {
    double value;
};

double inspect(const Counter& counter);
void increment(Counter& counter);

static Counter counter = Counter{41.0};

double inspect(const Counter& counter) {
    return counter.value;
}

void increment(Counter& counter) {
    (counter.value = (counter.value + 1.0));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    increment(counter);
    print(inspect(counter));
    return 0;
}
