// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Optional<double> findPositive(const std::vector<double>& arr);
ets::Optional<std::string> firstNonEmpty(const std::vector<std::string>& arr);

static std::vector<double> positives = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};
static std::vector<double> allNegative = std::vector<double>{std::move((-1.0)), std::move((-2.0)), std::move((-3.0))};
static std::vector<std::string> tags = std::vector<std::string>();
static std::vector<std::string> names = std::vector<std::string>{std::move(std::string("alice")), std::move(std::string("bob"))};
static ets::Optional<double> value = findPositive(std::vector<double>{std::move(5.0)});

ets::Optional<double> findPositive(const std::vector<double>& arr) {
    ets::Optional<double> result = optionalNone<double>();
    for (const auto& x : arr) {
        if (optionalIsPresent(result)) {
            break;
        }
        if ((x > 0.0)) {
            (result = optionalSome(x));
        }
    }
    return result;
}

ets::Optional<std::string> firstNonEmpty(const std::vector<std::string>& arr) {
    ets::Optional<std::string> result = optionalNone<std::string>();
    for (const auto& s : arr) {
        if (optionalIsPresent(result)) {
            break;
        }
        if ((length(s) > 0.0)) {
            (result = optionalSome(s));
        }
    }
    return result;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(optionalValueOr(findPositive(positives), (-1.0)));
    print(optionalValueOr(findPositive(allNegative), (-1.0)));
    print(optionalValueOr(firstNonEmpty(tags), std::string("(none)")));
    print(optionalValueOr(firstNonEmpty(names), std::string("(none)")));
    print(optionalValueOr(optionalMap(value, [=](double n) -> double { return (n * 2.0); }), 0.0));
    return 0;
}
