// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string greet(const std::string& name, const ets::Optional<std::string>& nickname);
std::string greetExplicit(const std::string& name, const ets::Optional<std::string>& nickname);
std::string config(const std::string& host, ets::Optional<double> port, ets::Optional<bool> tls);

std::string greet(const std::string& name, const ets::Optional<std::string>& nickname) {
    const auto prefix = optionalValueOr(nickname, std::string("(anon)"));
    return ets::concat(std::string("hello "), prefix, std::string(" ("), name, std::string(")"));
}

std::string greetExplicit(const std::string& name, const ets::Optional<std::string>& nickname) {
    const auto prefix = optionalValueOr(nickname, std::string("(anon)"));
    return ets::concat(std::string("hi "), prefix, std::string(" "), name);
}

std::string config(const std::string& host, ets::Optional<double> port, ets::Optional<bool> tls) {
    const auto p = optionalValueOr(port, 80.0);
    const auto t = optionalValueOr(tls, false);
    return ets::concat(host, std::string(":"), numberToString(p), (t ? std::string("/tls") : std::string("")));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(greet(std::string("alice"), ets::Optional<std::string>::none()));
    print(greet(std::string("bob"), std::string("bobby")));
    print(greetExplicit(std::string("carl"), ets::Optional<std::string>::none()));
    print(greetExplicit(std::string("dora"), optionalSome(std::string("D"))));
    print(config(std::string("api.example.com"), ets::Optional<double>::none(), ets::Optional<bool>::none()));
    print(config(std::string("api.example.com"), 443.0, ets::Optional<bool>::none()));
    print(config(std::string("api.example.com"), 443.0, true));
    return 0;
}
