// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::vector<double> a = std::vector<double>{std::move(1.0), std::move(2.0), std::move(3.0)};
static std::vector<double> b = std::vector<double>{std::move(4.0), std::move(5.0), std::move(6.0)};
static std::vector<double> combined = ([](std::vector<double> dst) -> std::vector<double> { dst.insert(dst.end(), (a).begin(), (a).end()); dst.insert(dst.end(), (b).begin(), (b).end()); return dst; })(std::vector<double>{});
static std::vector<double> prefix = ([](std::vector<double> dst) -> std::vector<double> { dst.push_back(0.0); dst.insert(dst.end(), (a).begin(), (a).end()); dst.push_back(99.0); return dst; })(std::vector<double>{});
static std::vector<double> mixed = ([](std::vector<double> dst) -> std::vector<double> { dst.push_back(10.0); dst.insert(dst.end(), (a).begin(), (a).end()); dst.push_back(20.0); dst.insert(dst.end(), (b).begin(), (b).end()); dst.push_back(30.0); return dst; })(std::vector<double>{});

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(length(combined));
    print(combined[static_cast<std::size_t>(0.0)]);
    print(combined[static_cast<std::size_t>(5.0)]);
    print(length(prefix));
    print(prefix[static_cast<std::size_t>(0.0)]);
    print(prefix[static_cast<std::size_t>(1.0)]);
    print(prefix[static_cast<std::size_t>(3.0)]);
    print(prefix[static_cast<std::size_t>(4.0)]);
    print(length(mixed));
    print(mixed[static_cast<std::size_t>(0.0)]);
    print(mixed[static_cast<std::size_t>(1.0)]);
    print(mixed[static_cast<std::size_t>(4.0)]);
    print(mixed[static_cast<std::size_t>(8.0)]);
    return 0;
}
