// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T>
concept Named = requires(T value) {
    { value.name() } -> std::same_as<std::string>;
};

template <typename T>
concept Aged = requires(T value) {
    { value.age() } -> std::same_as<double>;
};

static std::vector<double> ns = std::vector<double>{std::move(1.0), std::move(2.0), std::move(3.0)};
static std::variant<std::string, double> m = std::string("hello");
static std::tuple<std::string, double> p = std::make_tuple(std::string("a"), 1.0);

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(numberToString(length(ns)));
    print(m);
    print(std::get<0>(p));
    return 0;
}
