// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static double x = 42.0;

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(ets::typeofOf<double>());
    print(ets::typeofOf<std::string>());
    print(ets::typeofOf<bool>());
    print(ets::typeofOf<std::vector<double>>());
    print(ets::typeofOf<void>());
    return 0;
}
