// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<double> loadValue();
ets::Task<double> calculate();
ets::Task<void> notify(std::string message);

static double result = ets::syncWait(calculate());

ets::Task<double> loadValue() {
    co_return 21.0;
}

ets::Task<double> calculate() {
    const double value = (co_await loadValue());
    co_return (value * 2.0);
}

ets::Task<void> notify(std::string message) {
    print(message);
    co_return;
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    ets::syncWait(notify(std::string("async complete")));
    print(result);
    return 0;
}
