// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::function<double(double)> makeAdder(double amount);
std::function<double()> makeCounter(double start);

static std::function<double(double)> timesTwo = [](double value) -> double { return (value * 2.0); };
static std::function<double(double)> addTen = makeAdder(10.0);
static std::function<double()> counter = makeCounter(100.0);

std::function<double(double)> makeAdder(double amount) {
    return [=](double value) -> double { return (value + amount); };
}

std::function<double()> makeCounter(double start) {
    double count = start;
    return [&]() mutable -> double {
        (count = (count + 1.0));
        return count;
    };
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(std::string("Doble: "), timesTwo(6.0));
    print(std::string("Suma capturada: "), addTen(5.0));
    print(std::string("Contador: "), counter());
    print(std::string("Contador: "), counter());
    return 0;
}
