// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Motor {
    double power;

    std::string label() const {
        return std::string("motor");
    }
};

struct Car {
    Motor motor;
    std::string name;

    std::string description() const {
        return ets::concat((*this).name, std::string(" con "), (*this).motor.label());
    }
};

static Motor motor = Motor{120.0};
static Car car = Car{motor, std::string("Coupe")};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(car.description());
    print(car.motor.power);
    return 0;
}
