// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

struct Widget {
    double size;

    void constructor(double s) {
        ((*this).size = s);
    }

    double getOldSize() const {
std::cerr << "WARN: 'getOldSize' is deprecated: use size field instead\n";         return (*this).size;
    }

    void doNothing() const {
std::cerr << "WARN: 'doNothing' is deprecated: deprecated\n";     }
};

static Widget w = Widget{42.0};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(w.size);
    print(w.getOldSize());
    w.doNothing();
    return 0;
}
