// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static ets::Map<std::string, double> m = ets::Map<std::string, double>{};
static ets::Set<std::string> s = ets::Set<std::string>{};
static std::vector<double> xs = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    m.set(std::string("a"), 1.0);
    m.set(std::string("b"), 2.0);
    m.removeKey(std::string("a"));
    print(numberToString(m.size()));
    s.add(std::string("x"));
    s.add(std::string("y"));
    s.removeKey(std::string("x"));
    print(numberToString(s.size()));
    xs.erase(xs.begin() + static_cast<std::ptrdiff_t>(1.0));
    print(ets::concat(std::string("len="), numberToString(length(xs)), std::string(" first="), numberToString(xs[static_cast<std::size_t>(0.0)]), std::string(" second="), numberToString(xs[static_cast<std::size_t>(1.0)])));
    return 0;
}
