// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

enum class Color : int {
    Red = 0,
    Green = 5,
    Blue = 6
};

struct Direction {
    std::string value;
    Direction() = default;
    Direction(std::string v) : value(std::move(v)) {}
    operator const std::string&() const { return value; }
    static const Direction Up;
    static const Direction Down;
    static const Direction Left;
    static const Direction Right;
};
inline const Direction Direction::Up = Direction("UP");
inline const Direction Direction::Down = Direction("DOWN");
inline const Direction Direction::Left = Direction("LEFT");
inline const Direction Direction::Right = Direction("RIGHT");

static Color c = Color::Green;
static Direction d = Direction::Up;
static std::vector<Direction> all = std::vector<Direction>{std::move(Direction::Up), std::move(Direction::Down), std::move(Direction::Left), std::move(Direction::Right)};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(numberToString(static_cast<double>(c)));
    print(static_cast<std::string>(d));
    for (const auto& v : all) {
        print(static_cast<std::string>(v));
    }
    return 0;
}
