// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::vector<double> xs = std::vector<double>{std::move(1.0), std::move(2.0), std::move(3.0)};
static ets::Map<std::string, double> m = ets::Map<std::string, double>{};
static ets::Set<std::string> s = ets::Set<std::string>{};

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    for (const auto& x : xs) {
        print(numberToString(x));
    }
    for (char c : std::string("ab")) {
        print(c);
    }
    m.set(std::string("a"), 1.0);
    m.set(std::string("b"), 2.0);
    for (const auto& pair_pair : (m).data()) {
        auto pair = std::make_tuple(pair_pair.first, pair_pair.second);
        print(ets::concat(std::get<0>(pair), std::string("="), numberToString(std::get<1>(pair))));
    }
    s.add(std::string("x"));
    s.add(std::string("y"));
    for (const auto& v : (s).data()) {
        print(v);
    }
    return 0;
}
