// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T>
struct Box {
    T value;

    T get() const {
        return (*this).value;
    }
};

template <typename T>
T identity(const T& value);
template <typename T>
T first(const std::vector<T>& values);

static Box<double> numberBox = Box<double>{42.0};
static Box<std::string> textBox = Box<std::string>{std::string("generic")};
static std::vector<double> values = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};

template <typename T>
T identity(const T& value) {
    return value;
}

template <typename T>
T first(const std::vector<T>& values) {
    return values[static_cast<std::size_t>(0.0)];
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(std::string("Identidad: "), identity<std::string>(std::string("hola")));
    print(std::string("Explícito: "), identity<double>(7.0));
    print(std::string("Primero: "), first<double>(values));
    print(std::string("Caja number: "), numberBox.get());
    print(std::string("Caja string: "), textBox.get());
    return 0;
}
