// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

void checkString(const std::variant<std::string, double>& v);
void checkNumber(const std::variant<std::string, double>& v);
void checkClass();

static std::variant<std::string, double> v = std::string("hi");

void checkString(const std::variant<std::string, double>& v) {
    if (std::holds_alternative<std::string>(v)) {
        print(std::string("string"));
    } else {
        print(std::string("number"));
    }
}

void checkNumber(const std::variant<std::string, double>& v) {
    if (std::holds_alternative<double>(v)) {
        print(std::string("number"));
    } else {
        print(std::string("string"));
    }
}

void checkClass() {
    double x = 42.0;
    if (true /* instanceof sobre tipo no-union: etsc no tiene herencia */) {
        print(std::string("number-class"));
    } else {
        print(std::string("other"));
    }
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    checkString(v);
    (v = 42.0);
    checkNumber(v);
    checkClass();
    return 0;
}
