// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

template <typename T>
concept Named = requires(T value) {
    { value.name() } -> std::same_as<std::string>;
};

template <typename T>
concept Aged = requires(T value) {
    { value.age() } -> std::same_as<double>;
};

struct Person {
    std::string name() const {
        return std::string("Alice");
    }

    double age() const {
        return 30.0;
    }
};

struct Robot {
    std::string name() const {
        return std::string("R2D2");
    }

    double age() const {
        return 5.0;
    }
};

template <typename T>
requires Named<T> && Aged<T>
std::string describe(const T& value);

template <typename T>
requires Named<T> && Aged<T>
std::string describe(const T& value) {
    return ets::concat(value.name(), std::string(" ("), numberToString(value.age()), std::string(")"));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    console.log(describe<Person>(Person{}));
    console.log(describe<Robot>(Robot{}));
    return 0;
}
