// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string classify(double x);
std::string sign(double n);

std::string classify(double x) {
    return (x == 0.0 ? std::string("zero") : (x == 1.0 ? std::string("one") : (x == 2.0 ? std::string("two") : (x == 3.0 ? std::string("three") : std::string("many")))));
}

std::string sign(double n) {
    return (n == 0.0 ? std::string("zero") : (n == 1.0 ? std::string("one") : std::string("many")));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(classify(0.0));
    print(classify(1.0));
    print(classify(2.0));
    print(classify(3.0));
    print(classify(42.0));
    print(sign(0.0));
    print(sign(1.0));
    print(sign(2.0));
    print(sign(5.0));
    return 0;
}
