// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static std::string error = std::string("");
static std::string source = argument(1.0);
static std::string copy = ets::concat(source, std::string(".copy"));
static std::string moved = ets::concat(source, std::string(".moved"));
static std::string contents = std::string("");

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    if ((writeFile(source, std::string("hello"), error) == false)) {
        printError(error);
    } else {
        if ((appendFile(source, std::string(" native"), error) == false)) {
            printError(error);
        }
    }
    if (readFile(source, contents, error)) {
        write(std::string("Contenido: "));
        print(contents);
    }
    if ((copyFile(source, copy, error) && moveFile(copy, moved, error))) {
        print(std::string("Movido: "), fileExists(moved));
    }
    if ((removeFile(source, error) == false)) {
        printError(error);
    }
    if ((removeFile(moved, error) == false)) {
        printError(error);
    }
    if (((fail(std::string("error controlado"), error) == false) && hasError(error))) {
        writeError(std::string("Diagnóstico: "));
        printError(error);
    }
    clearError(error);
    return 0;
}
