// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static double READ = 1.0;
static double WRITE = 2.0;
static double EXEC = 4.0;
static double RWX = (static_cast<std::int64_t>((static_cast<std::int64_t>(READ) | static_cast<std::int64_t>(WRITE))) | static_cast<std::int64_t>(EXEC));

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(0xFF.0p0);
    print(0X1A.0p0);
    print(0xFFFFFF.0p0);
    print(63.0);
    print(7.0);
    print(10.0);
    print(15.0);
    print(1000000.0);
    print(1000.0);
    print((0x10.0p0 + 5.0));
    print((15.0 * 2.0));
    print((8.0 - 1.0));
    print((0xFF.0p0 - 63.0));
    print(RWX);
    print(((static_cast<std::int64_t>(RWX) & static_cast<std::int64_t>(READ)) > 0.0));
    print(((static_cast<std::int64_t>(RWX) & static_cast<std::int64_t>(8.0)) > 0.0));
    return 0;
}
