// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Optional<double> findFirstPositive(const std::vector<double>& arr);
ets::Optional<double> safeDivide(double a, double b);

static std::vector<double> positives = std::vector<double>{std::move(10.0), std::move(20.0), std::move(30.0)};
static ets::Optional<double> found = findFirstPositive(positives);
static std::vector<double> allNegative = std::vector<double>{std::move((-1.0)), std::move((-2.0)), std::move((-3.0))};
static ets::Optional<double> notFound = findFirstPositive(allNegative);
static ets::Optional<double> doubled = optionalMap(found, [](double n) -> double { return (n * 2.0); });
static ets::Optional<double> doubledEmpty = optionalMap(notFound, [](double n) -> double { return (n * 2.0); });
static ets::Optional<double> chain = optionalAndThen(found, [](double n) -> ets::Optional<double> { return safeDivide(n, 2.0); });
static ets::Optional<double> chainEmpty = optionalAndThen(notFound, [](double n) -> ets::Optional<double> { return safeDivide(n, 2.0); });
static ets::Optional<double> fallback = optionalOrElse(notFound, optionalSome(0.0));

ets::Optional<double> findFirstPositive(const std::vector<double>& arr) {
    ets::Optional<double> result = optionalNone<double>();
    for (const auto& x : arr) {
        if (optionalIsPresent(result)) {
            break;
        }
        if ((x > 0.0)) {
            (result = optionalSome(x));
        }
    }
    return result;
}

ets::Optional<double> safeDivide(double a, double b) {
    if ((b == 0.0)) {
        return optionalNone<double>();
    }
    return optionalSome((a / b));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(optionalValueOr(found, (-1.0)));
    print(optionalValueOr(notFound, (-1.0)));
    print(optionalValueOr(doubled, 0.0));
    print(optionalValueOr(doubledEmpty, 0.0));
    print(optionalIsPresent(doubledEmpty));
    print(optionalValueOr(chain, (-1.0)));
    print(optionalValueOr(chainEmpty, (-1.0)));
    print(optionalValueOr(fallback, (-1.0)));
    return 0;
}
