// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

ets::Task<double> delay(double ms, double value);
ets::Task<std::vector<double>> runAll();
ets::Task<double> runRace();
ets::Task<std::string> delayStr(double ms, std::string value);
ets::Task<std::vector<std::string>> runAllStrings();

static std::vector<double> numbers = ets::syncWait(runAll());
static double first = ets::syncWait(runRace());
static std::vector<std::string> letters = ets::syncWait(runAllStrings());

ets::Task<double> delay(double ms, double value) {
    (co_await sleep(ms));
    co_return value;
}

ets::Task<std::vector<double>> runAll() {
    co_return all(([](std::vector<ets::Task<double>> dst) -> std::vector<ets::Task<double>> { dst.push_back(std::move(delay(1.0, 10.0))); dst.push_back(std::move(delay(1.0, 20.0))); dst.push_back(std::move(delay(1.0, 30.0))); return dst; })(std::vector<ets::Task<double>>()));
}

ets::Task<double> runRace() {
    co_return race(([](std::vector<ets::Task<double>> dst) -> std::vector<ets::Task<double>> { dst.push_back(std::move(delay(100.0, 1.0))); dst.push_back(std::move(delay(100.0, 2.0))); dst.push_back(std::move(delay(100.0, 3.0))); return dst; })(std::vector<ets::Task<double>>()));
}

ets::Task<std::string> delayStr(double ms, std::string value) {
    (co_await sleep(ms));
    co_return value;
}

ets::Task<std::vector<std::string>> runAllStrings() {
    co_return all(([](std::vector<ets::Task<std::string>> dst) -> std::vector<ets::Task<std::string>> { dst.push_back(std::move(delayStr(1.0, std::string("alpha")))); dst.push_back(std::move(delayStr(1.0, std::string("beta")))); dst.push_back(std::move(delayStr(1.0, std::string("gamma")))); return dst; })(std::vector<ets::Task<std::string>>()));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    for (const auto& n : numbers) {
        print(numberToString(n));
    }
    print(numberToString(first));
    for (const auto& s : letters) {
        print(s);
    }
    return 0;
}
