// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string greet(const std::string& name, double age);
void demo();

std::string greet(const std::string& name, double age) {
    return ets::concat(std::string("Hola "), name, std::string(", tienes "), age, std::string(" años"));
}

void demo() {
    const std::string name = std::string("Mundo");
    const double count = 42.0;
    const bool flag = true;
    console.log(ets::concat(std::string("Hola "), name, std::string(", count="), count, std::string(", flag="), flag));
    console.log(ets::concat(std::string("Suma: "), (count + 8.0)));
    console.log(ets::concat(std::string("Doble: "), (count * 2.0)));
    const std::string inner = ets::concat(std::string("soy "), name);
    console.log(ets::concat(std::string("Anidado: "), inner));
    console.log(greet(std::string("Ana"), 30.0));
    console.log(ets::concat(std::string("Literal puro")));
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    demo();
    return 0;
}
