// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

static double x = 42.0;
static double y = 7.0;
static double z = 99.0;

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    print(numberToString(y));
    print(numberToString(z));
    return 0;
}
