// Generated by estatic-ts-cpp. Do not edit.
#include <iostream>
#include <string>
#include <vector>
#include <tuple>
#include <functional>
#include <cmath>
#include <concepts>
#include <utility>
#include "runtime/ets_runtime.hpp"

std::string describe(const std::variant<std::string, double>& value);

static std::variant<std::string, double> a = std::string("texto");
static std::variant<std::string, bool> b = std::string("abc");
static std::variant<std::string, double> c = std::string("ok");

std::string describe(const std::variant<std::string, double>& value) {
    if (true) {
        return std::string("string");
    }
    return std::string("number");
}

int main(int argc, char** argv) {
    ets_argc = argc;
    ets_argv = argv;
    console.log(describe(std::string("hola")));
    console.log(describe(42.0));
    console.log(std::string("a ="), a);
    (a = 100.0);
    console.log(std::string("a ="), a);
    console.log(std::string("b ="), b);
    (b = true);
    console.log(std::string("b ="), b);
    console.log(std::string("c ="), c);
    (c = 3.14);
    console.log(std::string("c ="), c);
    return 0;
}
